extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  indentation:
    indent-sequences: consistent
  document-start: disable
