version: 1
actions:
  - write_files:
      - path: ".github/workflows/autodocs-on-change.yml"
        mode: "100644"
        contents: |
          name: AutoDocs (on-change)

          on:
            workflow_dispatch: {}
            push:
              branches: [ "main" ]
              paths:
                - ".github/workflows/**"
                - ".github/autopatch/**"
                - "scripts/autodocs_generate.py"
                - ".github/taskops/ledger.jsonl"

          permissions:
            contents: write
            actions: read

          jobs:
            run:
              runs-on: ubuntu-latest

              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                  with:
                    fetch-depth: 0

                - name: Setup Python
                  uses: actions/setup-python@v5
                  with:
                    python-version: "3.11"

                - name: Generate docs (README + .github/docs/*)
                  run: |
                    set -euo pipefail
                    python - <<'PY'
                    import subprocess, sys, pathlib
                    root = pathlib.Path(".")
                    gen = root / "scripts" / "autodocs_generate.py"
                    if not gen.exists():
                        print("::error title=Missing generator::scripts/autodocs_generate.py not found")
                        sys.exit(1)
                    r = subprocess.run([sys.executable, str(gen)], text=True)
                    sys.exit(r.returncode)
                    PY

                - name: Commit changes (if any)
                  run: |
                    set -euo pipefail
                    git config user.name  "StegVerse Bot"
                    git config user.email "bot@stegverse.org"
                    if ! git diff --quiet; then
                      git add -A
                      git commit -m "docs(autodocs): auto-refresh after workflow/manifest change"
                      git push origin HEAD:main
                    else
                      echo "No changes to commit."
                    fi
  - commit:
      message: "chore(autodocs): add on-change auto-refresh workflow (push + manual)"
