version: 1
actions:
  - write_files:
      - path: "templates/commit_template.txt"
        mode: "100644"
        contents: |
          <type>(<scope>): <summary>
          # feat(api): add provider registry for hybrid bridge

          # Body (optional): details on what changed and why

          # Footer (optional): references, automation tags, etc.
          # Refs: #42
          # Signed-off-by: Name <email@example.com>
          # Version: v1.0
  - commit:
      message: "chore(templates): add universal commit template v1.0 (autopatch)"
