version: 1
actions:
  - write_files:
      - path: "templates/commit_template.txt"
        mode: "100644"
        contents: |
          <type>(<scope>): <summary>
          # feat(api): add provider registry for hybrid bridge
          #
          # Body (optional): what/why, key details, risks, follow-ups
          #
          # Footer (optional): references, automation tags, metadata
          # Refs: #42
          # Signed-off-by: Name <email@example.com>
          # Version: v1.1
  - commit:
      message: "chore(templates): add/refresh universal commit template v1.1 (autopatch)" DM
