version: 1
patches:
- id: remediate-autopatch-layout
  type: yaml
  file: .github/autopatch/remediate-autopatch-layout.patch.yml
  apply_to_repo_root: true
  enabled: true
- id: hybrid-collab-bridge-init
  type: yaml
  file: .github/autopatch/hybrid-bridge.patch.yml
  apply_to_repo_root: true
  enabled: true
- id: hybrid-collab-bridge-init
  enabled: true
  type: yaml
  file: .github/autopatch/hybrid-bridge.patch.yml
  apply_to_repo_root: true
  mode: apply
- id: hybrid-collab-bridge-init-v1
  enabled: true
  type: yaml
  file: .github/autopatch/hybrid-bridge.patch.yml
  apply_to_repo_root: true
  mode: apply
