version: 1
patches:
  - id: commit-template-upgrade-v1_1
    path: .github/autopatch/commit-template-upgrade-v1_1.patch.yml

  - id: commit-template
    path: .github/autopatch/commit-template.patch.yml

  - id: commit-template-config
    path: .github/autopatch/commit-template-config.patch.yml
