version: 1
patches:
  - .github/autopatch/patches/workflows-badge-wire.patch.yml
    - id: workflows-badges-legend
      path: .github/autopatch/workflows-badges-legend.patch.yml
    - id: validate-badges-readme
      path: .github/autopatch/validate-badges-readme.patch.yml
    - id: ops-console
      path: .github/autopatch/ops-console.patch.yml
    - id: inject-kick-dispatch
      path: .github/autopatch/inject-kick-dispatch.patch.yml
    - id: fix-yaml-bulk-autofix
      path: .github/autopatch/fix-yaml-bulk-autofix.patch.yml
    # Ensures Python setup is consistent across workflows & PyYAML always present
    - path: ".github/autopatch/patches/pyyaml-and-common-setup.patch.yml"
      reason: "Standardize Python env; fix recurring 'No module named yaml'"

