version: 1
patches:
  - id: hybrid-collab-bridge-init-v4   # bump id to avoid any caching
    enabled: true
    type: yaml
    path: .github/autopatch/hybrid-bridge.patch.yml
    apply_to_repo_root: true
