version: 1
patches:
  - id: docs-suite
    path: .github/autopatch/docs-suite.patch.yml
  - id: commit-template
    path: .github/autopatch/commit-template.patch.yml
  - id: commit-template
    path: .github/autopatch/commit-template.patch.yml
    
