version: 1
patches:
  - id: pr-safe-dispatch
      path: .github/autopatch/pr-safe-dispatch.patch.yml
  - id: pr-safe-inject
      path: .github/autopatch/pr-safe-inject.patch.yml
  - id: autodocs-prsafe-status
      path: .github/autopatch/autodocs-prsafe-status.patch.yml
  - id: taskops-autodocs-link
      path: .github/autopatch/taskops-autodocs-link.patch.yml
  - id: readme-ci-dashboard
    path: .github/autopatch/readme-ci-dashboard.patch.yml
