version: 1
patches:
  - id: reindex-nudge-bootstrap
    path: .github/autopatch/reindex-nudge-bootstrap.patch.yml
  - id: reindex-watchdog-bootstrap
    path: .github/autopatch/reindex-watchdog-bootstrap.patch.yml
