version: 1
patches:
  - .github/autopatch/patches/workflows-badge-wire.patch.yml
    - id: workflows-badges-legend
      path: .github/autopatch/workflows-badges-legend.patch.yml
    - id: validate-badges-readme
      path: .github/autopatch/validate-badges-readme.patch.yml
    - id: ops-console
      path: .github/autopatch/ops-console.patch.yml
