version: 1
actions:
  - write_files:
      # 1) Reindex Nudge workflow: runs on demand AND if you simply edit anything under .github/trigger/reindex/**
      - path: ".github/workflows/actions-reindex-nudge.yml"
        mode: "100644"
        contents: |
          name: actions-reindex-nudge

          on:
            workflow_dispatch:
              inputs:
                do_touch:
                  description: "Also commit a tiny timestamp file to .github/trigger/reindex/ to force a rescan"
                  required: false
                  default: "true"
            push:
              paths:
                - ".github/trigger/reindex/**"

          permissions:
            contents: write

          jobs:
            reindex:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                  with:
                    persist-credentials: true
                    fetch-depth: 0

                - name: Enumerate workflows (for logs)
                  run: |
                    echo "Listing workflow files under .github/workflows"
                    ls -la .github/workflows || true
                    echo "----"
                    echo "Dumping first lines of each workflow (helps GitHub re-index internally)"
                    for f in .github/workflows/*.yml .github/workflows/*.yaml; do
                      [ -f "$f" ] && head -n 30 "$f" || true
                    done

                - name: Optional touch (commit a nudge file to trigger re-scan)
                  if: ${{ github.event_name == 'workflow_dispatch' && inputs.do_touch == 'true' }}
                  run: |
                    set -euo pipefail
                    mkdir -p .github/trigger/reindex
                    TS="$(date -u +'%Y%m%dT%H%M%SZ')"
                    echo "reindex nudge at ${TS}" > .github/trigger/reindex/ping-${TS}.txt
                    git config user.name "StegVerse Bot"
                    git config user.email "bot@stegverse.org"
                    git add .github/trigger/reindex/ping-${TS}.txt
                    git commit -m "chore(actions): reindex nudge ${TS}"
                    git push origin HEAD:${{ github.ref_name || 'main' }}

                - name: Write quick report
                  run: |
                    mkdir -p self_healing_out
                    {
                      echo "{"
                      echo "  \"repo\": \"${GITHUB_REPOSITORY}\","
                      echo "  \"run_id\": \"${GITHUB_RUN_ID}\","
                      echo "  \"event\": \"${GITHUB_EVENT_NAME}\","
                      echo "  \"ref\": \"${GITHUB_REF}\","
                      echo "  \"ts\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\""
                      echo "}"
                    } > self_healing_out/ACTIONS_REINDEX_REPORT.json

                - name: Upload report
                  uses: actions/upload-artifact@v4
                  with:
                    name: actions_reindex_report_${{ github.run_id }}
                    path: self_healing_out/ACTIONS_REINDEX_REPORT.json
                    if-no-files-found: warn

      # 2) Tiny helper script (optional local use): creates the trigger file for you
      - path: "scripts/reindex_nudge.sh"
        mode: "100755"
        contents: |
          #!/usr/bin/env bash
          set -euo pipefail
          mkdir -p .github/trigger/reindex
          TS="$(date -u +'%Y%m%dT%H%M%SZ')"
          echo "reindex nudge at ${TS}" > .github/trigger/reindex/ping-${TS}.txt
          git add .github/trigger/reindex/ping-${TS}.txt
          git commit -m "chore(actions): reindex nudge ${TS}"
          echo "Created .github/trigger/reindex/ping-${TS}.txt (commit staged). Push when ready."

      # 3) Short README for how to use it (also visible in repo)
      - path: ".github/docs/REINDEX.md"
        mode: "100644"
        contents: |
          # ⚙️ Actions Reindex Nudge

          If a workflow's **Run workflow** button disappears, do one of:

          ## Option A — Click to run
          1. Go to **Actions → actions-reindex-nudge → Run workflow**.
          2. Leave **do_touch = true** (default). This commits a tiny timestamp file to `.github/trigger/reindex/` which forces an Actions rescan.

          ## Option B — No button available? Trigger by commit
          1. In the GitHub web UI, create or edit any file under `.github/trigger/reindex/`  
             Example: `.github/trigger/reindex/manual-ping.txt`
          2. Commit to `main`. The **actions-reindex-nudge** workflow will run due to the `push` path filter.

          ## Notes
          - This is safe; it does not modify workflows themselves.
          - Artifacts include a small JSON report under `actions_reindex_report_<run_id>`.
          - If your repo uses branch protections, ensure `contents: write` is allowed for Actions.

  - commit:
      message: "chore(actions): install Actions reindex nudge workflow & docs (autopatch)"
