version: 1
actions:
  - write_files:
      - path: ".github/workflows/taskops-ledger-hooks.yml"
        mode: "100644"
        contents: |
          name: taskops-ledger-hooks

          on:
            workflow_dispatch: {}
            workflow_run:
              workflows:
                - autopatch-apply
                - export-hcb
              types:
                - completed

          permissions:
            contents: write

          jobs:
            log:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                  with:
                    persist-credentials: true
                    fetch-depth: 0

                - name: Ensure TaskOps directory
                  shell: bash
                  run: |
                    set -euo pipefail
                    mkdir -p .github/taskops
                    [ -f .github/taskops/ledger.jsonl ] || : > .github/taskops/ledger.jsonl

                - name: Append ledger entry (workflow_run)
                  if: ${{ github.event_name == 'workflow_run' }}
                  shell: bash
                  run: |
                    set -euo pipefail
                    # Build a compact JSON line recording the originating run
                    REPO="${GITHUB_REPOSITORY}"
                    RUN_ID="${{ github.event.workflow_run.id }}"
                    RUN_URL="https://github.com/${REPO}/actions/runs/${RUN_ID}"
                    WF_NAME="${{ github.event.workflow_run.name }}"
                    CONCLUSION="${{ github.event.workflow_run.conclusion }}"
                    EVENT="${{ github.event.workflow_run.event }}"
                    BRANCH="${{ github.event.workflow_run.head_branch }}"
                    SHA="${{ github.event.workflow_run.head_sha }}"
                    ATTEMPT="${{ github.event.workflow_run.run_attempt }}"
                    TS="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

                    # Extra fields for export-hcb (if present in payload inputs)
                    # Safely extract via jq if available; otherwise leave blank.
                    EXPORT_BRANCH=""
                    SYNC_MODE=""
                    VERSION_TAG=""
                    if command -v jq >/dev/null 2>&1; then
                      echo '${{ toJson(github.event.workflow_run) }}' | jq -r '
                        (.pull_requests[0].head.ref // empty) as $pr |
                        . as $root |
                        "" ' >/dev/null 2>&1 || true
                    fi

                    printf '{"ts":"%s","event":"workflow_run","workflow":"%s","conclusion":"%s","repo":"%s","branch":"%s","sha":"%s","run_id":"%s","run_url":"%s","trigger_event":"%s","attempt":%s}\n' \
                      "$TS" "$WF_NAME" "$CONCLUSION" "$REPO" "$BRANCH" "$SHA" "$RUN_ID" "$RUN_URL" "$EVENT" "${ATTEMPT:-0}" \
                      >> .github/taskops/ledger.jsonl

                - name: Append ledger entry (manual dispatch of this logger)
                  if: ${{ github.event_name == 'workflow_dispatch' }}
                  shell: bash
                  run: |
                    set -euo pipefail
                    TS="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
                    printf '{"ts":"%s","event":"logger_ping","workflow":"taskops-ledger-hooks","repo":"%s","actor":"%s"}\n' \
                      "$TS" "$GITHUB_REPOSITORY" "$GITHUB_ACTOR" \
                      >> .github/taskops/ledger.jsonl

                - name: Commit ledger (if changed)
                  shell: bash
                  run: |
                    set -euo pipefail
                    git config user.name  "StegVerse Bot"
                    git config user.email "bot@stegverse.org"
                    git add .github/taskops/ledger.jsonl
                    if git diff --cached --quiet; then
                      echo "No ledger changes."
                    else
                      msg="chore(taskops): ledger update from ${{ github.event_name }} (${GITHUB_RUN_ID})"
                      git commit -m "$msg"
                      git push origin HEAD:main
                    fi

  - commit:
      message: "chore(taskops): add ledger hooks (log autopatch-apply & export-hcb workflow runs)"
