name: _reusable: Secret Scan (patterns)
on:
  workflow_call:
    inputs:
      patterns_path:
        type: string
        default: scripts/secret_patterns.json
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq ripgrep || true
      - name: Run scan
        run: |
          set -e
          mkdir -p self_healing_out
          OUT="self_healing_out/SECRET_SCAN.json"
          if [ -f "${{ inputs.patterns_path }}" ]; then
            PAT="$(jq -r '.patterns[]?' "${{ inputs.patterns_path }}" | tr '\n' '|' | sed 's/|$//')"
            if [ -n "$PAT" ]; then
              rg -n --no-messages -e "$PAT" -g '!self_healing_out/**' -g '!.git/**' > self_healing_out/SECRET_HITS.txt || true
            fi
          fi
          jq -n --arg file "self_healing_out/SECRET_HITS.txt" \
                --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
                '{ts:$ts, hits: ( ( (input_filename|fromjson?) | . ) // [] ) }' < /dev/null > "$OUT" 2>/dev/null || echo '{"ts":"'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'","hits":[]}' > "$OUT"
      - uses: ./.github/workflows/_reusables/upload-bundle.yml
        with:
          name: secret_scan
          paths: |
            self_healing_out/SECRET_HITS.txt
            self_healing_out/SECRET_SCAN.json
