name: Upload Sweep Bundle
description: "Reusable sweep uploader with placeholder support."

inputs:
  name:
    required: true
  base_dir:
    required: true
  files:
    required: true
  extra_globs:
    required: false
    default: ""
  create_placeholder:
    required: false
    default: "false"
  placeholder_msg:
    required: false
    default: "Sweep did not run"

runs:
  using: "composite"
  steps:
    - name: Ensure sweep dir
      shell: bash
      run: |
        mkdir -p "${{ inputs.base_dir }}"

    - name: Ensure placeholder if requested
      if: ${{ inputs.create_placeholder == 'true' }}
      shell: bash
      run: |
        set -e
        for f in ${{ inputs.files }}; do
          if [ ! -f "${{ inputs.base_dir }}/$f" ]; then
            echo "# Placeholder" > "${{ inputs.base_dir }}/$f"
            echo "${{ inputs.placeholder_msg }}" >> "${{ inputs.base_dir }}/$f"
          fi
        done

    - name: Upload Sweep
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: |
          ${{ inputs.base_dir }}/${{ inputs.files }}
          ${{ inputs.base_dir }}/${{ inputs.extra_globs }}
        if-no-files-found: warn
