name: "▶ Run a workflow"
description: "Safely trigger a workflow via the Dispatch Proxy"
labels: ["run:workflow"]
body:
  - type: input
    id: workflow
    attributes:
      label: Workflow filename
      description: "e.g. autopatch-apply.yml"
      placeholder: "autopatch-apply.yml"
    validations: { required: true }
  - type: input
    id: ref
    attributes:
      label: Branch / ref
      placeholder: "main"
      value: "main"
  - type: textarea
    id: inputs_json
    attributes:
      label: Optional inputs JSON
      description: "JSON passed to the workflow’s dispatch inputs"
      placeholder: "{ \"dry_run\": \"true\" }"
