name: Actions Permission Check

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Token permissions test starting..."
      
      - name: Try listing workflows
        run: |
          echo "Testing workflow access..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows \
               | head -n 25

      - name: Try to dispatch a self-test run
        run: |
          echo "Dispatching this same workflow via API..."
          curl -s -o /dev/null -w "%{http_code}" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               -d '{"ref":"main"}' \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/actions-permission-check.yml/dispatches

      - name: Done
        run: echo "Permission check complete ✅"
