name: AutoDocs (on-demand)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare directories
        run: |
          set -euo pipefail
          mkdir -p .github/docs/env
          echo "[Init] Ensured .github/docs/env directory exists"

      - name: Seed minimal AutoDocs if missing
        run: |
          if [ ! -f scripts/autodocs_generate.py ]; then
            echo "[Init] Creating minimal AutoDocs generator"
            mkdir -p scripts
            cat > scripts/autodocs_generate.py <<'PY'
#!/usr/bin/env python3
import pathlib, datetime, json
ROOT = pathlib.Path(".github/docs")
ROOT.mkdir(parents=True, exist_ok=True)
ENV = ROOT / "env"; ENV.mkdir(parents=True, exist_ok=True)
now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
(ROOT / "TASKOPS_STATUS.md").write_text(f"# TaskOps Status\n\nUpdated: {now}\n\n✅ AutoDocs initialized.\n", encoding="utf-8")
(ROOT / "LEDGER_LAST_20.md").write_text("# Last 20 ledger entries\n\n_None yet._\n", encoding="utf-8")
(ENV / "ENV_DIFF_LATEST.md").write_text("# Environment Drift (Latest)\n\n_None yet._\n", encoding="utf-8")
(ENV / "TASKOPS_ENV_DIFF.json").write_text(json.dumps({"generated": now}), encoding="utf-8")
print("[AutoDocs] Minimal docs generated successfully.")
PY
            chmod +x scripts/autodocs_generate.py
          else
            echo "[Init] autodocs_generate.py already exists — leaving intact."
          fi

      - name: Run AutoDocs generator
        run: |
          set -euo pipefail
          echo "[AutoDocs] Executing generator..."
          python scripts/autodocs_generate.py
          echo "[AutoDocs] Completed."

      - name: Show generated docs tree
        run: |
          echo "---- .github/docs ----"
          ls -R .github/docs || true
          echo
          echo "---- Preview TASKOPS_STATUS.md ----"
          head -n 25 .github/docs/TASKOPS_STATUS.md || true

      - name: Commit docs (if changed)
        run: |
          set -euo pipefail
          git config user.name  "StegVerse Bot"
          git config user.email "bot@stegverse.org"
          git add .github/docs || true
          if ! git diff --cached --quiet; then
            git commit -m "docs(autodocs): initialize or refresh AutoDocs outputs"
            git push origin HEAD:main
          else
            echo "[AutoDocs] No changes detected."
          fi

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: autodocs-${{ github.run_id }}
          path: .github/docs
          if-no-files-found: warn
