name: Autopatch Ops (self-heal workflows)

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"
      - "scripts/**"

# Global permissions — valid keys only
permissions:
  contents: write
  actions: write

jobs:
  self_heal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps (PyYAML)
        run: python -m pip install --upgrade pip pyyaml

      - name: Ensure output dir
        run: mkdir -p .github/autopatch_out

      - name: Run self-heal script
        id: heal
        run: |
          set -euo pipefail
          if [ ! -f scripts/self_heal.py ]; then
            echo "ERROR: scripts/self_heal.py not found"; exit 1
          fi
          python scripts/self_heal.py
          : > .github/autopatch_out/SELF_HEAL_SUMMARY.json || true

      - name: Commit & push changes (if any)
        run: |
          set -euo pipefail
          git config user.name  "StegVerse Bot"
          git config user.email "bot@stegverse.org"
          git add .github/workflows || true
          if ! git diff --cached --quiet; then
            git commit -m "autopatch(ops): self-heal workflow YAML + ensure workflow_dispatch"
            git push origin HEAD:main
            echo "Committed self-heal changes."
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "No self-heal changes to commit."
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Post summary
        if: always()
        run: |
          echo "## Autopatch Ops summary" >> "$GITHUB_STEP_SUMMARY"
          if [ -s ".github/autopatch_out/SELF_HEAL_SUMMARY.json" ]; then
            cat .github/autopatch_out/SELF_HEAL_SUMMARY.json >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No summary file found." >> "$GITHUB_STEP_SUMMARY"

  post_dispatch:
    needs: self_heal
    if: always() && needs.self_heal.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      workflows: write
      contents: read
    steps:
      - name: Dispatch follow-ups (console table + badges)
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          REF: ${{ github.ref_name || 'main' }}
        run: |
          set -euo pipefail
          for wf in workflows-console-table.yml workflows-badges.yml; do
            echo "Dispatching $wf..."
            curl -sS -X POST \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/actions/workflows/$wf/dispatches" \
              -d "{\"ref\":\"$REF\"}" || true
          done
          echo "Done."
