name: Autopatch Ops (self-heal workflows)

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"
      - "scripts/**"

# Needed to write edits back and (optionally) manage other workflows later
permissions:
  contents: write
  workflows: write

jobs:
  self_heal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps (PyYAML)
        run: python -m pip install --upgrade pip pyyaml

      - name: Run self-heal script
        id: heal
        run: python scripts/self_heal.py

      - name: Commit & push changes (if any)
        run: |
          set -euo pipefail
          if [ -f ".github/autopatch_out/ANY_CHANGES" ] && grep -q true .github/autopatch_out/ANY_CHANGES; then
            git config user.name  "StegVerse Bot"
            git config user.email "bot@stegverse.org"
            git add .github/workflows
            git commit -m "autopatch(ops): self-heal workflow YAML + ensure workflow_dispatch"
            git push origin HEAD:main
            echo "Committed self-heal changes."
          else
            echo "No self-heal changes to commit."
          fi

      - name: Post summary
        if: always()
        run: |
          echo "## Autopatch Ops summary" >> "$GITHUB_STEP_SUMMARY"
          if [ -f ".github/autopatch_out/SELF_HEAL_SUMMARY.json" ]; then
            echo >> "$GITHUB_STEP_SUMMARY"
            cat .github/autopatch_out/SELF_HEAL_SUMMARY.json >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No summary file found." >> "$GITHUB_STEP_SUMMARY"
          fi
