name: Deploy Multi (temporarily neutralized)
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploy steps temporarily disabled to fix parser errors."
          echo "We will re-enable once zero-secret/kv flow is finalized."
