name: Multi-Host Deploy & Purge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: Render UI
        if: ${{ secrets.RENDER_UI_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_UI_DEPLOY_HOOK }}" \
            -H "Content-Type: application/json" \
            -d '{"source":"github"}'

      - name: Render API
        if: ${{ secrets.RENDER_API_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_API_DEPLOY_HOOK }}" \
            -H "Content-Type: application/json" \
            -d '{"source":"github"}'

      - name: Render Worker
        if: ${{ secrets.RENDER_WORKER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_WORKER_DEPLOY_HOOK }}" \
            -H "Content-Type: application/json" \
            -d '{"source":"github"}'

      - name: Netlify UI (build hook)
        if: ${{ secrets.NETLIFY_BUILD_HOOK_UI != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.NETLIFY_BUILD_HOOK_UI }}"

      - name: Vercel UI (deploy hook)
        if: ${{ secrets.VERCEL_DEPLOY_HOOK_UI != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_UI }}"

      - name: Vercel API (deploy hook)
        if: ${{ secrets.VERCEL_DEPLOY_HOOK_API != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_API }}"

      - name: Purge Cloudflare (entire zone)
        if: ${{ secrets.CF_ZONE_ID != '' && secrets.CF_API_TOKEN != '' }}
        run: |
          curl -fsSL -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'

      - name: Wait for providers to warm up
        run: sleep 10

      - name: Smoke check API /whoami
        run: |
          curl -fsS https://scw-api.onrender.com/whoami | sed -e 's/.*/API OK: &/'

      - name: Smoke check UI /stegtalk.html
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" https://scw-ui.onrender.com/stegtalk.html)
          test "$code" = "200" || (echo "UI stegtalk.html not 200 ($code)" && exit 1)
          echo "UI OK: stegtalk.html"
