on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - ".github/autopatch/**"
      - "scripts/autopatch_runner.py"
      - ".github/trigger/autopatch/**"   # <— sentinel path
