name: docs-suite-on-complete

on:
  workflow_run:
    workflows:
      - hybrid-bridge-functional
      - smoke
      - hcb-pipeline
    types: [ completed ]

permissions:
  contents: write

jobs:
  regen-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Regenerate docs/INDEX.md (reuse same logic)
        run: |
          set -euo pipefail
          mkdir -p docs

          SHA_SHORT="$(git rev-parse --short HEAD)"
          DATE_UTC="$(date -u +%Y-%m-%d)"
          RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

          LINKS="- [Root README](./../README.md)"
          if [ -f "README-HCB.md" ]; then
            LINKS="${LINKS}\n- [Hybrid Bridge Playbook (README-HCB.md)](./../README-HCB.md)"
          fi
          if [ -f "hybrid-collab-bridge/README.md" ]; then
            LINKS="${LINKS}\n- [Hybrid Collab Bridge README](./../hybrid-collab-bridge/README.md)"
          fi

          cat > docs/INDEX.md <<'EOFMD'
          # Documentation Index

          This page is auto-generated by **docs-suite-on-complete**.

          ## Key Docs
          EOFMD

          printf "%b\n\n" "${LINKS}" >> docs/INDEX.md

          if [ -f "README-HCB.md" ]; then
            echo "## Excerpt: README-HCB.md (first section)" >> docs/INDEX.md
            awk '
              BEGIN{in=0}
              /^## /{ if(in==0){in=1; print; next} else {exit} }
              { if(in==1) print }
            ' README-HCB.md >> docs/INDEX.md || true
            echo "" >> docs/INDEX.md
          fi

          cat >> docs/INDEX.md <<EOFMD

          ---
          _Auto-generated on **${DATE_UTC}** from \`${SHA_SHORT}\`.  
          Source workflow: **${{ github.event.workflow_run.name }}**  
          Run: ${RUN_URL}_
          EOFMD

      - name: Commit changes (if any)
        run: |
          set -e
          git config user.name "docs-bot"
          git config user.email "bot@stegverse.local"
          if git diff --quiet -- docs/INDEX.md; then
            echo "No changes in docs/INDEX.md"
            exit 0
          fi
          git add docs/INDEX.md
          git commit -m "docs: (auto) refresh docs/INDEX.md after pipeline success"
          git push origin HEAD:main
