name: Emergency Orchestrator (stub)
on:
  workflow_dispatch:

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use Emergency Orchestrator LITE. This stub exists to resolve prior YAML errors."
