name: export-hcb-weekly

on:
  schedule:
    - cron: "30 3 * * 0"   # Sundays at 03:30 UTC
  workflow_dispatch:
    inputs:
      force_push:
        description: "Skip dry-run and push immediately"
        required: false
        default: "false"

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  precheck:
    if: ${{ github.event_name == 'schedule' && (github.event.inputs.force_push != 'true') }}
    uses: ./.github/workflows/export-hcb.yml
    secrets: inherit
    with:
      repos_csv: "StegVerse/hybrid-collab-bridge"
      export_branch: "main"
      sync_mode: "mirror"
      push_strategy: "direct"
      version_tag: "v1.2"
      dry_run: "true"      # run validations only
      tag_repo: "false"
      release_create: "false"

  push:
    needs: [precheck]
    if: ${{ always() && (needs.precheck.result == 'success' || github.event.inputs.force_push == 'true') }}
    uses: ./.github/workflows/export-hcb.yml
    secrets: inherit
    with:
      repos_csv: "StegVerse/hybrid-collab-bridge"
      export_branch: "main"
      sync_mode: "mirror"
      push_strategy: "direct"   # set "pr" to open a PR instead of direct push
      version_tag: "v1.2"
      dry_run: "false"          # actual push
      tag_repo: "true"
      release_create: "true"
