name: Fix-It (Precision Workflow Repair)

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - ".github/trigger/fixit/**"

permissions:
  contents: write

jobs:
  fixit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq || true
          python3 -V

      - name: Run Precision Fix-It
        run: |
          mkdir -p self_healing_out
          python3 scripts/validate_and_fix.py --apply || true

      - name: Upload Fix Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fixit_report
          path: |
            self_healing_out/WORKFLOW_FIX_REPORT.json
            self_healing_out/WORKFLOW_FIX_REPORT.md
          if-no-files-found: warn
