name: hcb-pipeline
on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - "hybrid-collab-bridge/**"
      - ".github/workflows/hcb-pipeline.yml"

permissions:
  contents: read

# Global env (available to all jobs/steps)
env:
  PYTHON_VERSION: "3.11"
  ADMIN_TOKEN: "test_token"
  HCB_PROVIDERS_PATH: "${{ github.workspace }}/hybrid-collab-bridge/providers.ci.yaml"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        working-directory: hybrid-collab-bridge/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Compile sources
        working-directory: hybrid-collab-bridge/api
        run: python -m compileall app
      - name: Boot API and hit /health
        working-directory: hybrid-collab-bridge/api
        run: |
          set -e
          uvicorn app.main:app --host 127.0.0.1 --port 8080 &
          SV_PID=$!
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:8080/health >/dev/null 2>&1; then
              break
            fi
            sleep 0.5
          done
          curl -fsS http://127.0.0.1:8080/health | tee /tmp/health.json
          kill $SV_PID || true
      - name: Upload smoke artifact
        uses: actions/upload-artifact@v4
        with:
          name: hcb_smoke_outputs
          path: /tmp/health.json

  functional:
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        working-directory: hybrid-collab-bridge/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Compile sources
        working-directory: hybrid-collab-bridge/api
        run: python -m compileall app
      - name: Boot API and run /v1/run
        working-directory: hybrid-collab-bridge/api
        run: |
          set -e
          echo "Using providers path: ${HCB_PROVIDERS_PATH}"
          uvicorn app.main:app --host 127.0.0.1 --port 8080 &
          SV_PID=$!
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:8080/health >/dev/null 2>&1; then
              break
            fi
            sleep 0.5
          done
          echo '>>> /health'
          curl -fsS http://127.0.0.1:8080/health | tee /tmp/health.json
          echo '>>> /v1/run'
          curl -fsS -X POST http://127.0.0.1:8080/v1/run \
            -H "Content-Type: application/json" \
            -H "X-ADMIN-TOKEN: ${ADMIN_TOKEN}" \
            -d '{"slug":"ci-functional","question":"Give a one-line project summary.","context":"HCB functional test","experts":["claude"],"strategy":"consensus","human_gate":true,"temperature":0.1}' \
            | tee /tmp/run.json
          kill $SV_PID || true
      - name: Upload functional artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hcb_functional_outputs
          path: |
            /tmp/health.json
            /tmp/run.json
