name: hybrid-bridge-ci
on:
  workflow_dispatch: {}
  push:
    paths:
      - "hybrid-collab-bridge/**"
      - ".github/workflows/hybrid_bridge_ci.yml"

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      ANTHROPIC_API_KEY: "dummy_key_for_import_only"
      ADMIN_TOKEN: "test_token"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: hybrid-collab-bridge/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile sources
        working-directory: hybrid-collab-bridge/api
        run: python -m compileall app

      - name: Boot API and hit /health
        working-directory: hybrid-collab-bridge/api
        run: |
          set -e
          uvicorn app.main:app --host 127.0.0.1 --port 8080 &
          SV_PID=$!
          for i in {1..20}; do
            if curl -fsS http://127.0.0.1:8080/health >/dev/null 2>&1; then
              break
            fi
            sleep 0.5
          done
          curl -fsS http://127.0.0.1:8080/health | tee /tmp/health.json
          kill $SV_PID || true
