name: Kick Autopatch Apply
on:
  workflow_dispatch: {}
jobs:
  kick:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch autopatch_apply.yml
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'autopatch_apply.yml',
              ref: 'main',
            })
