name: Kick YAML Bulk Autofix
run-name: "Kick: YAML Bulk Autofix 🚀"

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Optional note for this kick"
        required: false
        default: "manual"

permissions:
  contents: write

concurrency:
  group: kick-yaml-bulk-autofix
  cancel-in-progress: false

jobs:
  kick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create trigger file
        id: trigger
        shell: bash
        run: |
          set -euo pipefail
          TS="$(date -u +%Y%m%dT%H%M%SZ)"
          DIR=".github/trigger/yaml-bulk-autofix"
          mkdir -p "$DIR"
          FILE="$DIR/ping-${TS}.txt"
          echo "note=${{ github.event.inputs.note || 'manual' }}" > "$FILE"
          echo "actor=${{ github.actor }}" >> "$FILE"
          echo "sha=${GITHUB_SHA}" >> "$FILE"
          echo "ref=${GITHUB_REF}" >> "$FILE"
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "Created $FILE"

      - name: Commit & push trigger
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "StegVerse Bot"
          git config user.email "bot@stegverse.org"
          git add .github/trigger/yaml-bulk-autofix/
          git commit -m "chore(kick): trigger YAML bulk autofix from workflow $GITHUB_RUN_ID" || {
            echo "Nothing to commit (trigger already present)"; exit 0; }
          git push origin HEAD:main

      - name: Echo next step
        run: |
          echo "Pushed ${{ steps.trigger.outputs.file }}"
          echo "This push will match yaml-bulk-autofix.yml paths and start the autofix run."
