name: Neutralize Secrets-if (simple)
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  neutralize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Rewrite secrets-if guards (Python)
        run: |
          python3 - <<'PY'
import re, pathlib
root = pathlib.Path(".")
for wf in list(root.glob(".github/workflows/*.yml")) + list(root.glob(".github/workflows/*.yaml")):
    t = wf.read_text(encoding="utf-8")
    def repl(m):
        pre = m.group(1)
        return f"{pre}# TODO(auto): secrets-guard disabled to avoid parser error\n{pre}# {m.group(0).strip()}\n{pre}if: ${{ false }}\n"
    t2 = re.sub(r"^([ \t]*)if:\s*\$\{\{\s*secrets\.[^\}]+\}\}\s*$", repl, t, flags=re.MULTILINE)
    if t2 != t:
        wf.write_text(t2, encoding="utf-8")
PY

      - name: Commit changes
        run: |
          git config user.name "automation-bot"
          git config user.email "bot@stegverse.local"
          git add -A
          git commit -m "Neutralize secrets-if guards" || echo "No changes"
          git push origin HEAD:main
