name: Ops Console (dispatch any workflow)

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: "Workflow file name in .github/workflows (e.g. seed-steg-config.yml)"
        required: true
      ref:
        description: "Git ref to run on"
        required: false
        default: "main"

permissions:
  actions: write
  contents: read

jobs:
  kick:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch target workflow
        uses: actions/github-script@v7
        with:
          script: |
            const wf = core.getInput('workflow', { required: true });
            const ref = core.getInput('ref') || 'main';
            core.info(`Dispatching ${wf} on ref ${ref}…`);
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: wf,
              ref
            });
            core.info('OK – dispatch created.');
