name: Ops Console

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "Comma-separated workflow files to run (from .github/workflows)"
        required: true
        default: "autopatch_apply.yml,autodocs-on-demand.yml"
      ref:
        description: "Git ref to run on (branch or tag)"
        required: false
        default: "main"

permissions:
  actions: write
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Show plan
        run: |
          echo "Targets: ${{ github.event.inputs.targets }}"
          echo "Ref     : ${{ github.event.inputs.ref }}"
      - name: Trigger selected workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGETS: ${{ github.event.inputs.targets }}
          REF: ${{ github.event.inputs.ref }}
        run: |
          set -euo pipefail
          IFS=',' read -ra WF <<< "$TARGETS"
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"
          ref="${REF:-main}"

          for raw in "${WF[@]}"; do
            wf="$(echo "$raw" | xargs)"  # trim
            echo "==> Dispatching $wf on $ref"
            # POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
            code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" \
              -X POST \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/${owner}/${repo}/actions/workflows/${wf}/dispatches" \
              -d "{\"ref\":\"${ref}\",\"inputs\":{}}")
            if [ "$code" != "204" ]; then
              echo "::error title=Dispatch failed::${wf} -> HTTP ${code}"
              cat /tmp/resp.txt || true
              exit 1
            fi
            echo "Dispatched ${wf}"
          done
