name: QuickKick Sweep

on:
  workflow_dispatch:   # ← deliberately no {} (more tolerant)

permissions:
  contents: write

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Kick a set of workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL: ${{ github.repository }}   # owner/repo
          REF: ${{ github.ref_name }}
          TARGETS: |
            kick-autopatch.yml
            kick-yaml-bulk-autofix.yml
            workflows-console-table.yml
            workflows-badges.yml
            workflows-badges-nudge.yml
            validate-setup-common-python.yml
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${REPO_FULL%%/*}"
          REPO="${REPO_FULL##*/}"
          : > results.tsv

          while IFS= read -r wf; do
            wf="$(echo "$wf" | xargs)"; [ -z "$wf" ] && continue
            url="https://api.github.com/repos/${OWNER}/${REPO}/actions/workflows/${wf}/dispatches"

            code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" \
              -X POST \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              "${url}" \
              -d "{\"ref\":\"${REF}\"}")

            note=""
            case "$code" in
              204) result="OK";;
              422) result="NO_DISPATCH"; note="missing 'workflow_dispatch'";;
              403) result="DENIED"; note="check Actions → Workflow permissions (Read & write)";;
              *)   result="ERROR"; note="HTTP ${code}: $(tr -d '\n' </tmp/resp.txt | cut -c1-160)";;
            esac
            printf "%s\t%s\t%s\n" "$wf" "$result" "$note" >> results.tsv
          done <<< "$TARGETS"

          {
            echo "## QuickKick Sweep"
            echo ""
            echo "| Workflow | Result | Note |"
            echo "|---|---|---|"
            while IFS=$'\t' read -r a b c; do
              echo "| \`$a\` | $b | ${c:-} |"
            done < results.tsv
            echo ""
            echo "> If you see **DENIED**, flip **Settings → Actions → General → Workflow permissions → Read & write**."
          } >> "$GITHUB_STEP_SUMMARY"
