name: Repo Tree (on demand)

on:
  workflow_dispatch:
    inputs:
      commit_to_repo:
        description: "Also commit docs/STRUCTURE.md"
        required: false
        default: "true"
  push:
    paths:
      - ".github/trigger/autotree/**"

permissions:
  contents: write

jobs:
  tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tree || true

      - name: Generate repo tree to docs/STRUCTURE.md
        run: |
          mkdir -p docs
          {
            echo "# Repository Structure"
            echo
            echo '```text'
            # Limit depth for readability; ignore common noise
            tree -I 'node_modules|.git|__pycache__|venv|dist|build|.next|.cache' -L 4 --dirsfirst --charset ascii || true
            echo '```'
            echo
            echo "Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          } > docs/STRUCTURE.md

      - name: Upload structure artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo_structure
          path: docs/STRUCTURE.md

      - name: Add artifact summary
        if: always()
        run: |
          echo "## Artifact Outputs" >> $GITHUB_STEP_SUMMARY
          echo "- repo_structure (download from Artifacts panel)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Quick link" >> $GITHUB_STEP_SUMMARY
          echo "- [docs/STRUCTURE.md](./docs/STRUCTURE.md)" >> $GITHUB_STEP_SUMMARY

      - name: Commit docs/STRUCTURE.md
        if: ${{ github.event.inputs.commit_to_repo == 'true' || github.event_name == 'push' }}
        run: |
          git config user.name "repo-tree-bot"
          git config user.email "bot@stegverse.local"
          git add docs/STRUCTURE.md
          git diff --cached --quiet && echo "No changes to commit." || git commit -m "docs: update STRUCTURE.md"
          git push || true
