name: Self-Healing Scan (+ optional fixes)

on:
  workflow_dispatch:
    inputs:
      auto_fix:
        description: "Apply canonical fixes (writes files & logs)"
        required: false
        default: "false"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "api/**"
      - "public/diag.html"
      - "render.yaml"
      - "package.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
      - "package-lock.json"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Ensure scripts are executable (best-effort)
        run: |
          chmod +x scripts/*.sh 2>/dev/null || true
          chmod +x scripts/*.py 2>/dev/null || true

      - name: Run scanner
        run: python3 scripts/collect_self_healing.py

      - name: Apply fixes (optional)
        if: ${{ github.event.inputs.auto_fix == 'true' }}
        run: python3 scripts/apply_canonical_fixes.py

      - name: Re-scan (after fixes)
        if: ${{ github.event.inputs.auto_fix == 'true' }}
        run: python3 scripts/collect_self_healing.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: self_healing_manifest
          path: |
            self_healing_out/SELF_HEALING_MANIFEST.json
            self_healing_out/SELF_HEALING_MANIFEST.md
            self_healing_out/index.json
            self_healing_out/GAPS.json
            self_healing_out/REMEDIATIONS.md
          if-no-files-found: error
