name: setup-common-python
description: Standard Python setup with PyYAML
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - run: |
        python -m pip install --upgrade pip
        pip install pyyaml
      shell: bash
