name: setup-common-python
description: Standard Python setup with YAML libs
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install YAML dependencies
      shell: bash
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        pip install pyyaml || true
        python - <<'PY'
        try:
            import yaml
            print("PyYAML present ✅")
        except Exception:
            import subprocess, sys
            print("Installing fallback ruamel.yaml ...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", "ruamel.yaml"])
        PY
