name: Universal Fix-It (YAML Corrector + Sweep + Reports)

on:
  workflow_dispatch:
    inputs:
      apply_fixes:
        description: "Apply fixes in-place (otherwise dry run)"
        required: false
        default: "true"
      auto_commit:
        description: "Commit/push normalized workflows to main (else open PR)"
        required: false
        default: "false"
  push:
    branches: [ "main" ]
    paths:
      - ".github/trigger/universal-fixit/**"

permissions:
  contents: write
  pull-requests: write
  checks: write

concurrency:
  group: universal-fixit-${{ github.ref }}
  cancel-in-progress: true

env:
  RUN_UNIVERSAL_FIXIT: ${{ vars.RUN_UNIVERSAL_FIXIT || 'true' }}

jobs:
  fixit:
    if: ${{ env.RUN_UNIVERSAL_FIXIT == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure tools
        shell: bash
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y jq curl zip
          python3 -V
          python3 -m pip install --upgrade pip
          pip install ruamel.yaml yamllint

      - name: Install actionlint
        shell: bash
        run: |
          set -e
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
          mv actionlint /usr/local/bin/actionlint

      - name: Seed helper scripts if missing (safe fallbacks)
        shell: bash
        run: |
          set -e
          mkdir -p scripts self_healing_out
          # yaml_corrector_v2.py fallback (creates a tiny report only)
          if [ ! -f scripts/yaml_corrector_v2.py ]; then
            cat > scripts/yaml_corrector_v2.py <<'PY'
#!/usr/bin/env python3
import json, sys, os, time, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT/"self_healing_out"; OUT.mkdir(parents=True, exist_ok=True)
rep_md = OUT/"YAML_CORRECTOR_REPORT.md"
rep_js = OUT/"YAML_CORRECTOR_REPORT.json"
if "--apply" in sys.argv:
    rep_md.write_text("# YAML Corrector\n\n- Fallback ran (no real corrector present)\n- Mode: apply\n", encoding="utf-8")
else:
    rep_md.write_text("# YAML Corrector\n\n- Fallback ran (no real corrector present)\n- Mode: dry-run\n", encoding="utf-8")
rep_js.write_text(json.dumps({"fallback": True, "ts": int(time.time())}, indent=2), encoding="utf-8")
print("fallback-corrector: OK")
PY
            chmod +x scripts/yaml_corrector_v2.py
          fi
          # sweep_all_workflows.py fallback
          if [ ! -f scripts/sweep_all_workflows.py ]; then
            cat > scripts/sweep_all_workflows.py <<'PY'
#!/usr/bin/env python3
import json, time, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT/"self_healing_out"; OUT.mkdir(parents=True, exist_ok=True)
(OUT/"SWEEP_REPORT.json").write_text(json.dumps({"fallback": True, "ts": int(time.time())}, indent=2), encoding="utf-8")
(OUT/"SWEEP_REPORT.md").write_text("# Sweep Report\n\n- Fallback sweep executed.\n", encoding="utf-8")
print("fallback-sweep: OK")
PY
            chmod +x scripts/sweep_all_workflows.py
          fi
          # auto_fix_known_issues.py fallback
          if [ ! -f scripts/auto_fix_known_issues.py ]; then
            cat > scripts/auto_fix_known_issues.py <<'PY'
#!/usr/bin/env python3
import json, time, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT/"self_healing_out"; OUT.mkdir(parents=True, exist_ok=True)
(OUT/"AUTO_FIX_REPORT.json").write_text(json.dumps({"detected":[],"fixed":[],"skipped":[],"errors":[],"fallback":True,"ts":int(time.time())}, indent=2), encoding="utf-8")
(OUT/"AUTO_FIX_REPORT.md").write_text("# Auto-Fix Report\n\n- No known issues detected (fallback).\n", encoding="utf-8")
print("fallback-auto-fix: OK")
PY
            chmod +x scripts/auto_fix_known_issues.py
          fi

      - name: Run YAML Corrector (apply first)
        shell: bash
        run: |
          set -e
          mkdir -p self_healing_out
          if [ "${{ github.event.inputs.apply_fixes || 'true' }}" = "true" ]; then
            python3 scripts/yaml_corrector_v2.py --apply || true
          else
            python3 scripts/yaml_corrector_v2.py || true
          fi

      - name: Auto-fix known issues (YAML-001, etc.)
        shell: bash
        run: |
          set -e
          python3 scripts/auto_fix_known_issues.py || true
          [ -f self_healing_out/AUTO_FIX_REPORT.md ] || echo "# Auto-Fix Report\n\n(no known issues detected)" > self_healing_out/AUTO_FIX_REPORT.md
          [ -f self_healing_out/AUTO_FIX_REPORT.json ] || echo '{"detected":[],"fixed":[],"skipped":[],"errors":[]}' > self_healing_out/AUTO_FIX_REPORT.json

      - name: Validate workflows
        shell: bash
        continue-on-error: true
        run: |
          actionlint -color -shellcheck=
          yamllint -f parsable .github/workflows || true

      - name: Sweep all workflows (report)
        shell: bash
        run: |
          set -e
          python3 scripts/sweep_all_workflows.py || true

      - name: Commit or PR changes (if auto_commit=true AND apply_fixes=true)
        if: ${{ (github.event.inputs.auto_commit == 'true') && (github.event.inputs.apply_fixes == 'true') }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -e
          git config user.name "universal-fixit-bot"
          git config user.email "bot@stegverse.local"
          git add .github/workflows || true
          if git diff --cached --quiet; then
            echo "No workflow changes to commit."
          else
            git commit -m "chore: universal-fixit — normalize/repair workflows"
            git push origin HEAD:main || true
          fi

      - name: Upload Fix-It bundle (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: universal_fixit_bundle
          path: |
            self_healing_out/YAML_CORRECTOR_REPORT.*
            self_healing_out/AUTO_FIX_REPORT.*
            self_healing_out/SWEEP_REPORT.*
          if-no-files-found: warn
