name: validate-autopatch-manifest

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/autopatch/**"
      - "scripts/validate_manifest.py"
      - ".github/actions/setup-common-python/**"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use the composite action we created; it installs Python + PyYAML and
      # exposes an output "yaml_available" that we key off of below.
      - name: Setup common Python
        id: py
        uses: ./.github/actions/setup-common-python
        with:
          python-version: "3.11"
          cache: "true"

      # ✅ This is the line you asked for—wired in the right place
      - name: Validate manifest with Python
        if: ${{ steps.py.outputs.yaml_available == 'true' }}
        run: |
          echo "🧩 Running manifest validator..."
          python scripts/validate_manifest.py

      - name: Upload validation report
        if: always() && hashFiles('/tmp/manifest-report.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: autopatch-manifest-report
          path: /tmp/manifest-report.json
          if-no-files-found: warn
