name: Workflows First Aid (repair + dispatch)

on:
  workflow_dispatch:
    inputs:
      repair_mode:
        description: "dry-run or apply"
        required: false
        default: "apply"
        type: choice
        options: ["dry-run","apply"]

permissions:
  contents: write

jobs:
  first_aid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade pip pyyaml

      - name: Repair malformed YAML (pre-pass)
        run: |
          set -euo pipefail
          python scripts/patches/repair_workflow_yaml.py --dir ".github/workflows" $([ "${{ inputs.repair_mode }}" = "dry-run" ] && echo "--dry-run" || true)

      - name: Commit repaired files (if any)
        if: ${{ inputs.repair_mode != 'dry-run' && hashFiles('self_healing_out/YAML_REPAIR_CHANGED') != '' }}
        run: |
          set -euo pipefail
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .github/workflows/*.yml .github/workflows/*.yaml || true
          if git diff --cached --quiet; then
            echo "No repaired files to commit."
          else
            git commit -m "chore(workflows): auto-repair malformed YAML (first-aid)"
            git push
          fi

      - name: Inject workflow_dispatch where missing
        run: |
          set -euo pipefail
          python scripts/patches/ensure_workflow_dispatch.py

      - name: Commit dispatch injections (if any)
        if: hashFiles('self_healing_out/DISPATCH_INJECTED.txt') != ''
        run: |
          set -euo pipefail
          git config user.name  "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .github/workflows/*.yml .github/workflows/*.yaml || true
          if git diff --cached --quiet; then
            echo "No dispatch changes to commit."
          else
            git commit -m "chore(workflows): ensure workflow_dispatch on all non-reusable workflows"
            git push
          fi

      - name: Summary
        if: always()
        run: |
          echo "### First-Aid Summary" >> "$GITHUB_STEP_SUMMARY"
          if [ -f self_healing_out/YAML_REPAIR_REPORT.md ]; then
            cat self_healing_out/YAML_REPAIR_REPORT.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No repair report found._" >> "$GITHUB_STEP_SUMMARY"
          fi
