name: Workflows Badges (auto-nudge)

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"
      - ".github/badges/**"
      - "README.md"
  schedule:
    - cron: "17 9 * * *"  # daily check (09:17 UTC)
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write

jobs:
  nudge:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch the badge generator
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo:  context.repo.repo,
                workflow_id: "workflows-badges.yml",
                ref: context.ref.replace("refs/heads/","") || "main"
              });
              core.info("✅ Dispatched workflows-badges.yml successfully");
            } catch (e) {
              core.warning(`⚠️ Could not dispatch workflows-badges.yml: ${e.message}`);
            }
